#!/usr/bin/env bash

if ! test "$LOGTALKHOME"
then
	export LOGTALKHOME=/usr/share/logtalk
fi

if ! test "$LOGTALKUSER"
then
    export LOGTALKUSER="$HOME"/logtalk
fi

if grep --quiet "^2" "$LOGTALKUSER/VERSION.txt" 2> /dev/null; then
	swilgt -q -g "set_logtalk_flag(startup_message, banner), set_logtalk_flag(report, off), {loader}"
else
	swilgt -q -g "{loader}"
fi
